config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos do
    member do
      delete "destroy_image", to: "photos#destroy_image"
    end
  end
  resources :galleries
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "your_galleries", to: "galleries#your_galleries"

  # Defines the root path route ("/")
  root "galleries#index"
end

app/models/photo.rb
# == Schema Information
#
# Table name: photos
#
#  id         :bigint           not null, primary key
#  alt_text   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  photo_id   :integer
#  user_id    :bigint           not null
#
# Indexes
#
#  index_photos_on_photo_id  (photo_id) UNIQUE
#  index_photos_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Photo < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :galleries
  has_one_attached :image
  has_one_attached :thumbnail

  validates :image, presence: true, attached: true, content_type: [ "image/png", "image/jpeg" ]
  validates :alt_text, presence: true

  before_validation :alt_text_sanatiser

  def alt_text_sanatiser
    self.alt_text = ActionController::Base.helpers.strip_tags(alt_text)
  end

  # function to precompute thumbnails
  def create_thumbnail(photo)
      # generates the transformations to the thumbnail
      thumbnail = photo.image.variant(resize_to_limit: [ 100, 100 ]).processed
      thumbnail_blob = thumbnail.blob
      # downloads the image, applying the transformation
      download = StringIO.new(thumbnail.download)
      photo.thumbnail.attach(io: download, filename: thumbnail_blob.filename.to_s, content_type: thumbnail_blob.content_type)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!, only: %i[ edit update destroy create ]
  load_and_authorize_resource

  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @gallery = Gallery.find(params[:photo][:gallery_id])
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
    @gallery = Gallery.find(params[:gallery_id])
    @photo = Photo.find(params[:id])
  end

  # POST /photos or /photos.json
  def create
    @gallery_to_attach = Gallery.find_by(id: params[:photo][:gallery_id])
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    @photo.image.attach(params[:photo][:image])

    respond_to do |format|
      if @photo.save && @photo.image.attached?
        # links the photo to the gallery
        @gallery_to_attach.photos << @photo
        # performs the precomputation of the full size image and saves the thumbnail as a seperate attachment
        @photo.create_thumbnail(@photo)

        format.html { redirect_to gallery_path(@gallery_to_attach), notice: "Photo was successfully added." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    @gallery = Gallery.find(params[:photo][:gallery_id])
    respond_to do |format|
      if @photo.update(photo_params)
        @photo.create_thumbnail(@photo)
        format.html { redirect_to gallery_path(@gallery), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    @photo.destroy!

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path, status: :see_other, notice: "Photo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # DELETE /photos/:id/destroy_image(:format)
  def destroy_image
    @photo.image.purge
    @photo.thumbnail.purge
    @gallery = Gallery.find(params[:gallery_id])
    redirect_to edit_photo_path(@photo, gallery_id: @gallery.id), notice: "Image was removed successfully."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def photo_params
      params.require(:photo).permit(:photo_id, :alt_text, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true, html: { multipart: true }) do |form| %>
  <% if photo.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <% if !photo.image.attached? %>
      <%= form.label :image, style: "display: block"%>
      <%= form.file_field :image, accept: "image/*", multiple: false, required: true %>
    <% else %>
      <div class="d-flex flex-column item">
        <div class="d-flex justify-content-center bg-light" style="width:105px; height:105px;">
            <button type="button"
              class="full-image-display"
              style="width:100px; height:100px;"
              data-bs-toggle="modal"
              data-bs-target="#display-image"
              data-image-url="<%= url_for(photo.image) %>"
              data-image-alt="<%= photo.alt_text %>">
              
            <% if photo.thumbnail.attached? %>
                <%= image_tag photo.thumbnail, alt: photo.alt_text, style: "max-width:100%; max-height:100%; object-fit:cover;" %>
            <% else %> 
                <div class="card text-center" style="width: 100px; height: 100px">
                <p>No Thumbnail Available</p>
                </div>
            <% end %>
            </button>
        </div>
        
      </div>
    <% end %>
  </div>

  <%# moved out here as it generates its own form and causes csrf token error %>
  <% if photo.image.attached? %>
    <%= link_to "Delete", destroy_image_photo_path(photo, gallery_id: gallery.id), method: :delete, class: "btn px-1 btn-danger", style: "width:46;" %>
  <% end %>

  <div>
    <%= form.label :alt_text, style: "display: block" %>
    <%= form.text_field :alt_text, required: true %>
  </div>

  <%= form.hidden_field :gallery_id, value: gallery.id %>

  <div class="py-2">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<div id="<%= dom_id photo %>">
  <p>
    <strong>Photo:</strong>
    <%= photo.photo_id %>
  </p>

  <p>
    <strong>Alt text:</strong>
    <%= photo.alt_text %>
  </p>

  <p>
    <strong>User:</strong>
    <%= photo.user_id %>
  </p>

</div>

app/views/photos/edit.html.erb
<% content_for :title, "Editing photo" %>

<h1>Editing photo</h1>

<%= render "form", photo: @photo, gallery: @gallery %>

<br>

<div>
    <%= link_to "Back to Gallery", gallery_path(@gallery), class: "btn-sm" %>

app/views/photos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Photos" %>

<h1>Photos</h1>

<div id="photos">
  <% @photos.each do |photo| %>
    <%= render photo %>
    <p>
      <%= link_to "Show this photo", photo %>
    </p>
  <% end %>
</div>

<%= link_to "New photo", new_photo_path %>

app/views/photos/new.html.erb
<% content_for :title, "New photo" %>

<h1>New photo</h1>


<br>

<div>
  <%= link_to "Back to photos", photos_path %>
</div>

app/views/photos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @photo %>

<div>
  <%= link_to "Edit this photo", edit_photo_path(@photo) %> |
  <%= link_to "Back to photos", photos_path %>

  <%= button_to "Destroy this photo", @photo, method: :delete %>
</div>