config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos do
    member do
      delete "destroy_image", to: "photos#destroy_image"
    end
  end
  resources :galleries
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "your_galleries", to: "galleries#your_galleries"

  # Defines the root path route ("/")
  root "galleries#index"
end

app/models/gallery.rb
# == Schema Information
#
# Table name: galleries
#
#  id          :bigint           not null, primary key
#  description :string
#  hidden      :boolean
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  gallery_id  :integer
#  user_id     :bigint           not null
#
# Indexes
#
#  index_galleries_on_gallery_id  (gallery_id) UNIQUE
#  index_galleries_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Gallery < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :photos

  validates :description, presence: true

  before_validation :description_sanatiser


  def description_sanatiser
    self.description = ActionController::Base.helpers.strip_tags(description)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_action :authenticate_user!, only: %i[ new edit update destroy create ]
  load_and_authorize_resource

  # GET /galleries or /galleries.json
  def index
    # paramters passed in to prevent sql injection
    @galleries = Gallery.where("hidden = ?", false)
  end

  # GET /your_galleries
  def your_galleries
    @galleries = Gallery.where("user_id = ?", current_user.id)
  end

  # GET /galleries/1
  def show
    # photo object is stored here (and regenerated each page refresh) for the photo uploading
    @gallery = Gallery.find(params[:id])
    @photo = Photo.new
    @gallery_photos = @gallery.photos
  end

  # GET /galleries/new
  def new
    @gallery = Gallery.new
  end

  # GET /galleries/1/edit
  def edit
  end

  # POST /galleries or /galleries.json
  def create
    @gallery = Gallery.new(gallery_params)
    @gallery.user_id = current_user.id

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: "Gallery was successfully created." }
        format.json { render :show, status: :created, location: @gallery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /galleries/1 or /galleries/1.json
  def update
    respond_to do |format|
      if @gallery.update(gallery_params)
        format.html { redirect_to @gallery, notice: "Gallery was successfully updated." }
        format.json { render :show, status: :ok, location: @gallery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1 or /galleries/1.json
  def destroy
    @gallery.destroy!

    respond_to do |format|
      format.html { redirect_to galleries_path, status: :see_other, notice: "Gallery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gallery
      @gallery = Gallery.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def gallery_params
      params.expect(gallery: [ :gallery_id, :name, :hidden, :description ])
    end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/views/galleries/_form.html.erb
<h2 class="card-title">New Gallery</h2>
<div class="card-body">
  <%= form_with(model: gallery) do |form| %>
  <% if gallery.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>
      <ul>
          <% gallery.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block"%>
    <%= form.text_field :name, placeholder: "Enter a Name", required: true %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, placeholder: "Enter a short description", required: true %>
  </div>

  <div>
    <%= form.label :hidden, style: "display: block" %>
    <%= form.checkbox :hidden %>
    <p>Want to keep your gallery private? Check this box!</p>
  </div>

  <div>
    <%= form.submit %>
  </div>
    <% end %>
  </div>
</div>

app/views/galleries/_gallery.html.erb
<div id="<%= dom_id gallery %>">

  <p>
    <strong>Name:</strong>
    <%= gallery.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= gallery.description %>
  </p>

  <p>
    <% if !current_user.nil? && !@gallery.nil? && current_user.id == @gallery.user_id %>
      <strong>Public:</strong>
      <%= !gallery.hidden %>
    <% end %>
  </p>

  <p>
    <div class="d-flex flex-wrap">
      <% @gallery_photos.each do |photo| %>
        <div class="d-flex flex-column item">
          <div class="d-flex justify-content-center bg-light" style="width:105px; height:105px;">
            <button type="button"
              class="full-image-display"
              style="width:100px; height:100px;"
              data-bs-toggle="modal"
              data-bs-target="#display-image"
              data-image-url="<%= url_for(photo.image) %>"
              data-image-alt="<%= photo.alt_text %>">

              <% if photo.thumbnail.attached? %>
                <%= image_tag photo.thumbnail, alt: photo.alt_text, style: "max-width:100%; max-height:100%; object-fit:cover;" %>
              <% else %> 
                <div class="card text-center" style="width: 100px; height: 100px">
                  <p>No Thumbnail Available</p>
                </div>
              <% end %>
            </button>
          </div>
          <div class="d-flex">
            <% if !current_user.nil? && !@gallery.nil? && current_user.id == @gallery.user_id %>
              <%= link_to "Edit", edit_photo_path(photo, gallery_id: gallery.id), class: "btn btn-primary px-1 ms-1 me-2", style: "width:46;"%>
              <%= button_to "Delete", photo_path(photo), method: :delete, class: "btn px-1 btn-danger", style: "width:46;" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </p>
  <%# Only occurs when user is logged in, and the gallery exists, and the user owns the gallery %>
  <% if !current_user.nil? && !@gallery.nil? && current_user.id == @gallery.user_id %>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#photo-form">Upload a photo</button>
  <% end %>
</div>

<% if !current_user.nil? && !@gallery.nil? && current_user.id == @gallery.user_id %>
  <div class="modal fade" id="photo-form" tabindex=-1>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title">Upload a photo</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "photos/form", photo: @photo, gallery: @gallery %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="modal fade" id="display-image" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div id="title" class="modal-title">
          <!-- Alt text here-->
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div id="url-marker" class="modal-body d-flex justify-content-center">
        <!-- Image here -->
      </div>
      <div id="footer" class="modal-footer">
        <!-- dynamic destroy button here -->
      </div>
    </div>
  </div>
</div>

app/views/galleries/edit.html.erb
<% content_for :title, "Editing gallery" %>

<h1>Editing gallery</h1>

<%= render "form", gallery: @gallery %>

<br>

<div>
  <%= link_to "Show this gallery", @gallery %> |
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/index.html.erb
<% content_for :title, "Galleries" %>

<h2>Galleries</h2>

<div id="galleries">
  <% @galleries.each do |gallery| %>
    <div class="card px-2 pt-2 my-2">
        <div class="card-title">
            <%= link_to gallery.name, gallery_path(gallery) %>
        </div>
        <div class="card-text">
            <%= gallery.description %>
        </div>
    </div>
  <% end %>
</div>
<% if !current_user.nil? && !@gallery.nil? && current_user.id == @gallery.user_id %>
  <%= link_to "New gallery", new_gallery_path %>
<% end %>

app/views/galleries/new.html.erb
<% content_for :title, "New gallery" %>

<%= render "form", gallery: @gallery, photo: @photo %>

<br>

<div>
  <%= link_to "Back to galleries", galleries_path %>
</div>

app/views/galleries/show.html.erb
<%= render @gallery %>

<div>
  <% if !current_user.nil? && current_user.id == @gallery.user_id %>
    <%= link_to "Edit this gallery", edit_gallery_path(@gallery) %> |
    <%= link_to "Back to galleries", galleries_path %>

    <%= button_to "Destroy this gallery", @gallery, method: :delete %>
  <% end %>
</div>

app/views/galleries/your_galleries.erb
<% content_for :title, "Your Galleries" %>

<h2>Your Galleries</h2>

<% @galleries.each do |gallery| %>
  <div class="card pt-2">
      <div class="card-title">
          <%= link_to gallery.name, gallery_path(gallery) %>
      </div>
      <div class="card-text">
          <%= gallery.description %>
      </div>
  </div>
<% end %>