config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :photos do
    member do
      delete "destroy_image", to: "photos#destroy_image"
    end
  end
  resources :galleries
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "your_galleries", to: "galleries#your_galleries"

  # Defines the root path route ("/")
  root "galleries#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Image Gallery" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">


    <%# font import for title %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quintessential&display=swap" rel="stylesheet">

    <%# Includes shakapacker application file %>
    <%= javascript_pack_tag "application", "data-turbo-track": "reload" %>
    <%# uses bootstrap CDN to avoid shakapacker depreciation warnings%>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <%= stylesheet_pack_tag "application", "data-turbo-track": "reload" %>

    
  </head>

  


  <body class="d-flex flex-column min-vh-100">

    <nav class="navbar-nav navbar-expand-lg py-3 bg-info">
      <ul class="navbar-nav">
        <li class="nav-item mx-2">
          <%= link_to "Galleries", galleries_path ,class: "nav-link" %>
        </li>
        <% if current_user.nil? == false %>
          <li class="nav-item me-2">
            <%= link_to "Create New Gallery", new_gallery_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-2">
            <%= link_to "Your Galleries", your_galleries_path, class: "nav-link" %>
          </li>
          <li class="nav-item me-2">
              <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item me-2">
              <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
          </li>
          <% end %>
      </ul>
    </nav>

    <div class="flex-grow-1">
      <% flash.each do |key, message| %>
        <div class="alert alert-<%= key %>"><%= message %></div>
      <% end %>
      <div id="login" class="d-flex flex-column justify-content-center align-items-center pt-5">
        <h1 class="quintessential-regular pb-4">Curate-A-Gallery</h1>
        <div class="card px-3 py-3 bg-light">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="mt-auto bg-gradient bg-success" style="height:80;">
      <p>&copy; Joshua Rylance</p>
    </footer>
    
    <!-- javascript bootstrap CDN here so the html is processed before the javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
  </body>
  
</html>